---
title: Thoughts on the Voyant Tutorial
date: 2014-10-11
author: Jennifer Farman
layout: post
---

The Voyant tutorial was a great introduction to digital text analysis, and after completing the tutorial I am definitely looking forward to learning about more powerful analytic tools that I can use in my digital history project. I chose to use text files from Project Gutenberg as the corpora for the tutorial, and since we are only a few weeks away from Halloween I felt that Gothic horror would be appropriate. So I downloaded the text of Marie Shelly's *Frankenstein* along with a few volumes of Edgar Allen Poe's complete works. After using Voyant's tool to remove stop words, I was able to get an excellent overview of the words used in both texts. Below is a word cloud generated by Voyant for the most common words in *Frankenstein*:

![word cloud](https://drive.google.com/a/stanford.edu/file/d/0B_dOqmSs3ifnRDAzeGc3cmN6SVU)

The word cloud does not necessarily give a good sense for the plot, and it would be difficult to extrapolate the historical context or significance of the work from this data visualization alone. It does, however, give a general overview for the thematic content of the work, and certainly illuminates the novel's Gothic elements.

Using the comparison / difference tool was also a fascinating exercise. If we look at the most common words in *Frankenstein* (excluding stop words), we see that *man*, *father*, *life*, *eyes*, *time*, *night*, and *mind* top the list. This information alone gives us useful information about the novel, but we can learn even more when we compare it to another work. After adding the first two volumes of Poe's completed works as a secondary document, I was able to see what the words with the greatest absolute "difference" value, i.e. which words were most unique to each document.

Looking at the difference values, we can see that for *Frankenstein*, the terms *father*, *feelings*, *miserable*, *dear*, *life*, *misery*, *friends*, *happiness*, and *love* are more frequent to *Frankenstein* then they are to the corpus as a whole. One possible interpretation of this data is that *Frankenstein* is more concerned with human emotion than Poe's work. Although one would need a more rigorous analysis of the text in order to present this as a conclusion, this data gives us an excellent starting point for analyzing similarities and differences between the texts.

The insights I mentioned above reflect the utility of Voyant as a tool for digital historians. However, tools like Voyant are limited by an inability to extract context. Voyant would be able to tell me if the words king and aristocracy appeared frequently in a seventeenth-century book, but it would not necessarily be able to tell me whether these terms were mentioned in a positive or negative light. Although the Voyant tutorial did reflect some of the limitations of digital historical tools, it only scratched the surface of what machine learning and NLP can do for historians. As AI, machine learning, and NLP continues to improve, historians will have even more powerful and effective tools at their fingertips.

